=== didierrc/U-SEW/Escritorio-Virtual/xml/rutas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="https://www.uniovi.es" elementFormDefault="qualified" targetNamespace="https://www.uniovi.es" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<xs:element name="rutas">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="ruta" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="ruta">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="duracion" />
				<xs:element ref="agencia" />
				<xs:element ref="descripcion" />
				<xs:element ref="adecuaciones" />
				<xs:element ref="inicio" />
				<xs:element ref="referencias" />
				<xs:element ref="recomendacion" />
				<xs:element ref="hitos" />
			</xs:sequence>

			<xs:attribute name="nombre" type="xs:string" use="required" />
			<xs:attribute name="tipo" type="xs:string" use="required" />
			<xs:attribute name="medioTransporte" type="xs:string" use="required" />
			<xs:attribute name="fechaInicio" type="xs:date" />
			<xs:attribute name="horaInicio" type="xs:time" />
		</xs:complexType>
	</xs:element>

	<xs:element name="duracion" type="xs:duration" />
	<xs:element name="agencia" type="xs:string" default="Sin Agencia" />
	<xs:element name="descripcion" type="xs:string" />

	<xs:element name="adecuaciones">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="adecuacion" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="adecuacion" type="xs:string" />

	<xs:element name="inicio">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="lugar" />
				<xs:element ref="direccion" />
				<xs:element ref="coordenadas" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="lugar" type="xs:string" />
	<xs:element name="direccion" type="xs:string" />

	<xs:element name="coordenadas">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="longitud" />
				<xs:element ref="latitud" />
				<xs:element ref="altitud" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="longitud" type="xs:double" />
	<xs:element name="latitud" type="xs:double" />
	<xs:element name="altitud">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="0" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="referencia" type="xs:string" />
	
	<xs:element name="recomendacion">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="0" />
				<xs:maxInclusive value="10" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="hitos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="hito" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="hito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="descripcion" />
				<xs:element ref="coordenadas" />
				<xs:element ref="distanciaHitoAnterior" />
				<xs:element ref="galeria" />
			</xs:sequence>
			<xs:attribute name="nombre" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="distanciaHitoAnterior">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:double">
					<xs:attribute name="unidades" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<xs:element name="galeria">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="fotografias" />
				<xs:element minOccurs="0" maxOccurs="1" ref="videos" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="fotografias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="foto" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="foto" type="xs:string" />
	
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="3" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="video" type="xs:string"/>
</xs:schema>

=== didierrc/U-SEW/Escritorio-Virtual/xml/rutasEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<rutas xmlns="https://www.uniovi.es" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="https://www.uniovi.es rutas.xsd">
    <ruta nombre="Ruta de la Cultura" tipo="Parques y monumentos" medioTransporte="A pie">
        <duracion>P1D</duracion>
        <agencia>Sin agencia</agencia>
        <descripcion> Para comenzar con nuestro itinerario de viaje por Mónaco, puede participar en
            la rica herencia y cultura de esta ciudad opulenta y lujosa. </descripcion>
        <adecuaciones>
            <adecuacion>Se puede ir con niños.</adecuacion>
            <adecuacion>Tercera edad.</adecuacion>
            <adecuacion>Se recomienda chaqueta.</adecuacion>
            <adecuacion>Se recomienda unos eurillos para ciertos museos.</adecuacion>
        </adecuaciones>
        <inicio>
            <lugar>Jardines Exóticos de Mónaco</lugar>
            <direccion>62 Bd du Jardin Exotique, 98000 Monaco</direccion>
            <coordenadas>
                <longitud>7.413956731788746</longitud>
                <latitud>43.73150501474114</latitud>
                <altitud>129</altitud>
            </coordenadas>
        </inicio>
        <referencias>
            <referencia>https://www.iconicriviera.com/es/itinerario-de-viaje-a-m%C3%B3naco/</referencia>
            <referencia>https://www.iconicriviera.com/es/jardines-famosos-de-los-parques-de-monacos/</referencia>
            <referencia>https://mapcarta.com/es/18984022</referencia>
        </referencias>
        <recomendacion>10</recomendacion>
        <hitos>
            <hito nombre="Jardines Exoticos de Monaco">
                <descripcion> Ábrete camino por los sinuosos senderos del Jardín Exótico. Puedes ver
                    plantas exóticas y suculentas aquí en este jardín mientras disfrutas de
                    impresionantes vistas de Mónaco y el mar. </descripcion>
                <coordenadas>
                    <longitud>7.413956731788746</longitud>
                    <latitud>43.73150501474114</latitud>
                    <altitud>129</altitud>
                </coordenadas>
                <distanciaHitoAnterior unidades="m">0</distanciaHitoAnterior>
                <galeria>
                    <fotografias>
                        <foto>jardin-exotico.jpg</foto>
                    </fotografias>
                </galeria>
            </hito>

            <hito nombre="Museo de Antropologia Prehistorica">
                <descripcion> A continuación, diríjase al Musée d'Anthropologie Préhistorique. La
                    exhibición incluye hallazgos arqueológicos, artefactos y fósiles. El Museo es
                    también un instituto de investigación, realizando trabajos de excavación y
                    estudios de laboratorio. Las colecciones recorren, a lo largo de la era de los
                    períodos glacial e interglacial, las principales etapas de la evolución de la
                    raza humana. Muestran que la Costa Azul también fue un gran lugar para vivir
                    para nuestros antepasados, incluso hace un millón de años. </descripcion>
                <coordenadas>
                    <longitud>7.413907822175449</longitud>
                    <latitud>43.73235711084301</latitud>
                    <altitud>111</altitud>
                </coordenadas>
                <distanciaHitoAnterior unidades="m">90</distanciaHitoAnterior>
                <galeria>
                    <fotografias>
                        <foto>museo-antropologia.jpg</foto>
                    </fotografias>
                </galeria>
            </hito>

            <hito nombre="Museo de Arte Villa Paloma">
                <descripcion> Cerca de la ladera del Jardín Exótico se encuentra esta villa con un
                    tono blanco perla. Es parte del Nouveau Museé National de Monaco. Alberga
                    exhibiciones de arte contemporáneo, a menudo con temas que se centran en
                    cuestiones ambientales. </descripcion>
                <coordenadas>
                    <longitud>7.413804572478769</longitud>
                    <latitud>43.73287349900603</latitud>
                    <altitud>129</altitud>
                </coordenadas>
                <distanciaHitoAnterior unidades="m">160</distanciaHitoAnterior>
                <galeria>
                    <fotografias>
                        <foto>villa-paloma.jpg</foto>
                    </fotografias>
                </galeria>
            </hito>

            <hito nombre="Parque Princesa Antonieta">
                <descripcion> Experimente la diversión y la relajación en este hermoso parque
                    ajardinado. Los niños pueden jugar en el parque infantil o con animales de
                    granja en el zoológico infantil, mientras juegas al minigolf. Ábrete camino
                    desde la parte superior del parque hasta el fondo. </descripcion>
                <coordenadas>
                    <longitud>7.414663944272216</longitud>
                    <latitud>43.733660668423084</latitud>
                    <altitud>110</altitud>
                </coordenadas>
                <distanciaHitoAnterior unidades="m">54</distanciaHitoAnterior>
                <galeria>
                    <fotografias>
                        <foto>parque-antonieta.jpg</foto>
                    </fotografias>
                </galeria>
            </hito>

            <hito nombre="Palacio del Principe de Monaco">
                <descripcion> El palacio real de Mónaco se encuentra en la cima de The Rock, con
                    vistas al Mediterráneo.El palacio, que fue construido como fortaleza en 1162,
                    originalmente estaba destinado a convertirse en una fortaleza de la República de
                    Génova. Este edificio ha conocido durante su historia, bombardeos y asedios por
                    parte de muchas fuerzas extranjeras. </descripcion>
                <coordenadas>
                    <longitud>7.420356220386329</longitud>
                    <latitud>43.731327732219476</latitud>
                    <altitud>64</altitud>
                </coordenadas>
                <distanciaHitoAnterior unidades="km">1</distanciaHitoAnterior>
                <galeria>
                    <fotografias>
                        <foto>palacio-principe.jpg</foto>
                    </fotografias>
                </galeria>
            </hito>

            <hito nombre="Catedral de San Nicolas">
                <descripcion> Una iglesia histórica de la fe católica romana, también alberga un
                    gran órgano de cuatro teclados. Los conciertos y servicios espirituales están
                    acompañados por las armonías de este magnífico gran órgano. Fíjese en el retablo
                    del pintor niçois Louis Bréa que data de 1500 y el Trono Episcopal realizado en
                    mármol blanco de Carrara de la Toscana, Italia. </descripcion>
                <coordenadas>
                    <longitud>7.422480048289593</longitud>
                    <latitud>43.730149028118774</latitud>
                    <altitud>66</altitud>
                </coordenadas>
                <distanciaHitoAnterior unidades="m">230</distanciaHitoAnterior>
                <galeria>
                    <fotografias>
                        <foto>catedral-monaco.jpg</foto>
                    </fotografias>
                </galeria>
            </hito>


        </hitos>

    </ruta>

    <ruta nombre="Ruta de la Lujuria" tipo="Casinos, centros comerciales y jardines"
        medioTransporte="A pie">

        <duracion>P1D</duracion>
        <agencia>Sin agencia</agencia>
        <descripcion> Después de ver los lugares emblemáticos de la ciudad, pase el día siguiente en
            nuestro itinerario de viaje disfrutando de la vida lujoa que ofrece Mónaco. Escaparate
            de lo extravagante centro comercial, con sus glamurosas boutiques. Luego, experimente la
            emoción de jugar un juego o tomar una copa en el casino después. </descripcion>
        <adecuaciones>
            <adecuacion>No es recomendado para niños</adecuacion>
            <adecuacion>Llevar dinero. Souvenirs y copas por todos lados.</adecuacion>
        </adecuaciones>
        <inicio>
            <lugar>One Monte-Carlo</lugar>
            <direccion>1 Pl. du Casino, 98000 Monaco</direccion>
            <coordenadas>
                <longitud>7.426605551725244</longitud>
                <latitud>43.73964337411425</latitud>
                <altitud>50</altitud>
            </coordenadas>
        </inicio>
        <referencias>
            <referencia>https://www.iconicriviera.com/es/itinerario-de-viaje-a-m%C3%B3naco/</referencia>
            <referencia>https://mapcarta.com/es/W308214647</referencia>
            <referencia>https://www.iconicriviera.com/es/centros-comerciales-m%C3%B3naco/</referencia>
        </referencias>
        <recomendacion>3</recomendacion>
        <hitos>
            <hito nombre="One Monte-Carlo">
                <descripcion> Comience su día en Casino Square, con un hermoso paseo comercial
                    marcado por varios edificios curvos y modernos. Es un lugar para ver las mejores
                    marcas del mundo con las tiendas más opulentas y exclusivas del distrito. </descripcion>
                <coordenadas>
                    <longitud>7.426605551725244</longitud>
                    <latitud>43.73964337411425</latitud>
                    <altitud>50</altitud>
                </coordenadas>
                <distanciaHitoAnterior unidades="m">0</distanciaHitoAnterior>
                <galeria>
                    <fotografias>
                        <foto>one-monte.jpg</foto>
                    </fotografias>
                </galeria>
            </hito>

            <hito nombre="Pequeños Jardines de Africa">
